### PR TITLE
Features & fixes

### LINKED ISSUE #30: Build fails (with recent EUMM?)
I see build failures on smoker machines where Crypt-MatrixSSL3-v3.7.6 formerly built and tested OK. Excerpt of the log:
```
cc -c  -I. -Iinc/matrixssl-3-7-2b-open -Iinc/matrixssl-3-7-2b-open/crypto -D_REENTRANT -D_GNU_SOURCE -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -Os -Wp,-w -fomit-frame-pointer -fPIC -I./ -I../ -O2   -DVERSION=\"v3.7.6\" -DXS_VERSION=\"v3.7.6\" -fPIC "-I/opt/perl-5.18.2t/lib/5.18.2/x86_64-linux-thread-multi/CORE"  -DUSE_TLS_RSA_WITH_AES_128_CBC_SHA -DUSE_TLS_RSA_WITH_AES_256_CBC_SHA -DUSE_TLS_RSA_WITH_AES_128_CBC_SHA256 -DUSE_TLS_RSA_WITH_AES_256_CBC_SHA256 -DUSE_TLS_RSA_WITH_AES_128_GCM_SHA256 -DUSE_TLS_RSA_WITH_AES_256_GCM_SHA384 -DUSE_TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA -DUSE_TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA -DUSE_TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384 -DUSE_TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256 -DUSE_TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 -DUSE_TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 -DUSE_TLS_DHE_PSK_WITH_AES_256_CBC_SHA -DUSE_TLS_DHE_PSK_WITH_AES_128_CBC_SHA -DUSE_TLS_DHE_RSA_WITH_AES_256_CBC_SHA -DUSE_TLS_DHE_RSA_WITH_AES_128_CBC_SHA -DUSE_TLS_DHE_RSA_WITH_AES_128_CBC_SHA256 -DUSE_TLS_DHE_RSA_WITH_AES_256_CBC_SHA256 -DUSE_AES -DUSE_AES_GCM -DUSE_3DES -DUSE_DES -DUSE_ARC4 -DUSE_RC2 -DUSE_SHA1 -DUSE_SHA256 -DUSE_SHA384 -DUSE_SHA512 -DUSE_MD5 -DUSE_HMAC -DUSE_ECC -DUSE_DH -DUSE_RSA -DUSE_X509 -DUSE_BASE64_DECODE -DUSE_CERT_PARSE -DUSE_FULL_CERT_PARSE -DUSE_PRIVATE_KEY_PARSING -DMATRIX_USE_FILE_SYSTEM -DUSE_CLIENT_SIDE_SSL -DUSE_SERVER_SIDE_SSL -DUSE_TLS -DUSE_TLS_1_1 -DUSE_TLS_1_2 -DDISABLE_SSLV3 -DUSE_STATELESS_SESSION_TICKETS -DENABLE_SECURE_REHANDSHAKES -DENABLE_TLS_FALLBACK_SCSV -DREQUIRE_SECURE_REHANDSHAKES -DENABLE_CERTIFICATE_STATUS_REQUEST -DENABLE_SIGNED_CERTIFICATE_TIMESTAMP -DUSE_ALPN -DENABLE_FALSE_START -DUSE_BEAST_WORKAROUND -DUSE_CLIENT_AUTH -DSERVER_CAN_SEND_EMPTY_CERT_REQUEST -DSERVER_WILL_ACCEPT_EMPTY_CLIENT_CERT_MSG -DUSE_PKCS5 -DUSE_PKCS8 -DUSE_PKCS12 -DPS_PUBKEY_OPTIMIZE_FOR_FASTER_SPEED -DPS_AES_IMPROVE_PERF_INCREASE_CODESIZE -DPS_3DES_IMPROVE_PERF_INCREASE_CODESIZE -DPS_MD5_IMPROVE_PERF_INCREASE_CODESIZE -DPS_SHA1_IMPROVE_PERF_INCREASE_CODESIZE -DLINUX -DPOSIX -DPSTM_64BIT  MatrixSSL3.c 
rm -f blib/arch/auto/Crypt/MatrixSSL3/MatrixSSL3.so
cc  -shared -O2 -L/usr/local/lib -fstack-protector -o blib/arch/auto/Crypt/MatrixSSL3/MatrixSSL3.so  inc/matrixssl-3-7-2b-open/core/corelib.o inc/matrixssl-3-7-2b-open/core/memset_s.o inc/matrixssl-3-7-2b-open/core/POSIX/osdep.o inc/matrixssl-3-7-2b-open/crypto/digest/hmac.o inc/matrixssl-3-7-2b-open/crypto/digest/md2.o inc/matrixssl-3-7-2b-open/crypto/digest/md4.o inc/matrixssl-3-7-2b-open/crypto/digest/md5.o inc/matrixssl-3-7-2b-open/crypto/digest/sha1.o inc/matrixssl-3-7-2b-open/crypto/digest/sha224.o inc/matrixssl-3-7-2b-open/crypto/digest/sha256.o inc/matrixssl-3-7-2b-open/crypto/digest/sha384.o inc/matrixssl-3-7-2b-open/crypto/digest/sha512.o inc/matrixssl-3-7-2b-open/crypto/hardware/aesni.o inc/matrixssl-3-7-2b-open/crypto/keyformat/asn1.o inc/matrixssl-3-7-2b-open/crypto/keyformat/base64.o inc/matrixssl-3-7-2b-open/crypto/keyformat/x509.o inc/matrixssl-3-7-2b-open/crypto/math/pstm.o inc/matrixssl-3-7-2b-open/crypto/math/pstm_montgomery_reduce.o inc/matrixssl-3-7-2b-open/crypto/math/pstm_mul_comba.o inc/matrixssl-3-7-2b-open/crypto/math/pstm_sqr_comba.o inc/matrixssl-3-7-2b-open/crypto/prng/prng.o inc/matrixssl-3-7-2b-open/crypto/prng/yarrow.o inc/matrixssl-3-7-2b-open/crypto/pubkey/dh.o inc/matrixssl-3-7-2b-open/crypto/pubkey/ecc.o inc/matrixssl-3-7-2b-open/crypto/pubkey/pkcs.o inc/matrixssl-3-7-2b-open/crypto/pubkey/pubkey.o inc/matrixssl-3-7-2b-open/crypto/pubkey/rsa.o inc/matrixssl-3-7-2b-open/crypto/symmetric/aes.o inc/matrixssl-3-7-2b-open/crypto/symmetric/aesGCM.o inc/matrixssl-3-7-2b-open/crypto/symmetric/arc4.o inc/matrixssl-3-7-2b-open/crypto/symmetric/des3.o inc/matrixssl-3-7-2b-open/crypto/symmetric/idea.o inc/matrixssl-3-7-2b-open/crypto/symmetric/rc2.o inc/matrixssl-3-7-2b-open/crypto/symmetric/seed.o inc/matrixssl-3-7-2b-open/matrixssl/cipherSuite.o inc/matrixssl-3-7-2b-open/matrixssl/dtls.o inc/matrixssl-3-7-2b-open/matrixssl/hsHash.o inc/matrixssl-3-7-2b-open/matrixssl/matrixssl.o inc/matrixssl-3-7-2b-open/matrixssl/matrixsslApi.o inc/matrixssl-3-7-2b-open/matrixssl/prf.o inc/matrixssl-3-7-2b-open/matrixssl/psk.o inc/matrixssl-3-7-2b-open/matrixssl/sslDecode.o inc/matrixssl-3-7-2b-open/matrixssl/sslEncode.o inc/matrixssl-3-7-2b-open/matrixssl/sslv3.o inc/matrixssl-3-7-2b-open/matrixssl/tls.o MatrixSSL3.o  \
	   -lpthread   \
	  
cc: error: inc/matrixssl-3-7-2b-open/core/corelib.o: No such file or directory
cc: error: inc/matrixssl-3-7-2b-open/core/memset_s.o: No such file or directory
cc: error: inc/matrixssl-3-7-2b-open/core/POSIX/osdep.o: No such file or directory
cc: error: inc/matrixssl-3-7-2b-open/crypto/digest/hmac.o: No such file or directory
...
cc: error: inc/matrixssl-3-7-2b-open/matrixssl/sslv3.o: No such file or directory
cc: error: inc/matrixssl-3-7-2b-open/matrixssl/tls.o: No such file or directory
make: *** [blib/arch/auto/Crypt/MatrixSSL3/MatrixSSL3.so] Error 1
```
It seems that this happens with newer ExtUtils::MakeMaker versions (e.g. 7.14) (@bingos: FYI)

### PR DESCRIPTION
**Pull request by vonydev**
fix #30

### CODE REVIEW

File: Makefile.PL [hunk 1]
```diff
@@ -360,6 +360,9 @@ if (-d 'inc/patches') {
         for my $file (glob 'inc/patches/*.patch') {
             # replacing \n with \n will change \n to \r\n on Win, without this patch.exe will crash
             system "cd \Q$mxbase\E && perl -pe \"s/\\n/\\n/\" ../../\Q$file\E | patch -p1 -N";
+
+            # some Windows systems don't like the path escape ...
+            # system "cd $mxbase && perl -pe \"s/\\n/\\n/\" ../../$file | patch -p1 -N";
```
Comment (powerman) [inline Makefile.PL]: Is this issue still happens on your system? Which Windows and Perl versions do you have on this system? Maybe you're running this using some other shell instead of standard command.com (like cygwin or powershell)?

File: Makefile.PL [hunk 2]
```diff
@@ -486,9 +489,9 @@ sub c_o {
     my $inherited = shift->SUPER::c_o(@_);
 
     if ($^O =~ /Win32/ms && $Config{cc} eq 'cl') {  # Microsoft deprecated -o in favor of /Fo
-        $inherited =~ s{\$\*\.c\n}{/Fo\$\*.obj \$\*.c\n}msg;
+        $inherited =~ s{\$\*\.c[\s\t]*$}{/Fo\$\*.obj \$\*.c\n}msg;
```
Comment (powerman) [inline Makefile.PL]: `\s` already include `\t`, so `[\s\t]*` can be simplified to `\s*`. Also I suppose real issue on Windows was not in `\t` but in `\r`, as usually, so `\r?\n` instead of `[\s\t]*$` will probably also works and will be much more clear.

File: examples/functions.pl [hunk 3]
```diff
@@ -188,6 +191,41 @@ sub ssl_io {
...
+            # handshake "Finished" message without waiting for the server's own
+            # handshake "Finished" message. This saves a rountrip and speeds the
+            # data transfer in some cases by 33%
+
+            my $rc2 = $ssl->false_start_received_data($buf);
+
+            # all the codes are already explained in this function
+            while (1) {
+                if ($rc2 == MATRIXSSL_APP_DATA) {
+                    $appIn .= $buf if (defined($buf));
```
Comment (powerman) [inline examples/functions.pl]: How `$buf` can be undefined if `$rc2 == MATRIXSSL_APP_DATA` - is `false_start_received_data()` actually works this way?

File: MatrixSSL3.xs [hunk 4]
```diff
@@ -1189,6 +1189,14 @@ Crypt_MatrixSSL3_Sess *sess_new_server(keys, certValidator)
     OUTPUT:
     RETVAL
 
+SV *get_master_secret(ssl)
```
Comment (powerman) [inline MatrixSSL3.xs]: Is this feature should be undocumented?

File: inc/patches/matrixssl_matrixsslConfig.h.patch [hunk 5]
```diff
@@ -12,6 +12,24 @@
...
  /* #define USE_TLS_RSA_WITH_AES_128_GCM_SHA256 */ /* TLS 1.2 */
  /* #define USE_TLS_RSA_WITH_AES_256_GCM_SHA384 */ /* TLS 1.2 */
+@@ -224,14 +224,14 @@ extern "C" {
+ 	SSL_SESSION_ENTRY_LIFE is in milliseconds, minimum 0
+ 
+ */
+-#define SSL_SESSION_TABLE_SIZE	32
+-#define SSL_SESSION_ENTRY_LIFE	86400 * 1000 /* one day */
++/* #define SSL_SESSION_TABLE_SIZE	32 */
++/* #define SSL_SESSION_ENTRY_LIFE 	86400 * 1000 */ /* one day */
```
Comment (powerman) [inline inc/patches/matrixssl_matrixsslConfig.h.patch]: Maybe `ifndef` will be better here, so it won't break if Makefile.PL won't provide these defines?

File: Makefile.PL (hunk 1 above)
Comment (vonydev) [inline Makefile.PL]: Windows 7, Perl 5.12.4, Visual Studio 10. It's just the standard command line. I put it there just because I'm getting tired to switch the escapes on/off. Now it's just moving the # 3 lines up.

File: Makefile.PL (hunk 2 above)
Comment (vonydev) [inline Makefile.PL]: There is an actual \s at the end of the Makefile line. No way around it. I've changed from [\s\t]* to \s* tho.

File: examples/functions.pl (hunk 3 above)
Comment (vonydev) [inline examples/functions.pl]: Not anymore. Fixed.

File: MatrixSSL3.xs (hunk 4 above)
Comment (vonydev) [inline MatrixSSL3.xs]: Let's call it experimental for now. No need to document it.

File: inc/patches/matrixssl_matrixsslConfig.h.patch (hunk 5 above)
Comment (vonydev) [inline inc/patches/matrixssl_matrixsslConfig.h.patch]: Nice fix. Done.
